[build]
  command = "npm run build" # Your existing build command for the React app
  publish = "dist"          # Your existing publish directory for the React app

[functions]
  directory = "netlify/functions" # This tells Netlify where your functions code lives
  node_bundler = "esbuild"      # Recommended for faster builds and smaller bundles
  # IMPORTANT: Mark @google/generative-ai as external. This tells esbuild NOT to bundle it,
  # as it's expected to be a Node.js module available in the Netlify runtime.
  external_node_modules = ["@google/generative-ai"]
